# Generated by Django 3.1.3 on 2020-11-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='task',
            field=models.TextField(verbose_name='Где остановиться'),
        ),
    ]
