# Generated by Django 3.1.3 on 2020-11-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201115_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='Где_поесть',
            field=models.CharField(choices=[('1', 'Макдоналдс'), ('2', 'Имбирь'), ('3', 'Роял Пасс'), ('4', 'Роза ветров'), ('5', 'Шашлычная Тандыр'), ('6', 'Пахлава'), ('7', 'Coffee like')], default='1', max_length=2),
        ),
    ]
