# Generated by Django 3.1.3 on 2020-11-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201115_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='Комментарий',
            field=models.TextField(default='Удобно', max_length=123123),
        ),
    ]
