# Generated by Django 3.1.3 on 2020-11-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tour_комментарий'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='тур',
        ),
        migrations.AddField(
            model_name='tour',
            name='Туроператор',
            field=models.TextField(default='', max_length=123123),
        ),
        migrations.AlterField(
            model_name='tour',
            name='Где_остановиться',
            field=models.TextField(default='', max_length=123123),
        ),
        migrations.AlterField(
            model_name='tour',
            name='Где_поесть',
            field=models.TextField(default='', max_length=123123),
        ),
    ]
