# Generated by Django 3.1.3 on 2020-11-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201115_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='Комментарий',
            field=models.TextField(default='', max_length=123123),
        ),
    ]
